### PR TITLE
Respect RStudio console width

### LINKED ISSUE #9: Respect RStudio console width
e.g.

```R
console_width <- function() {
  rstudio <- Sys.getenv("RSTUDIO_CONSOLE_WIDTH")
  if (identical(rstudio, "")) {
    getOption("width", 80)
  } else {
    as.integer(rstudio)
  }
}
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #9

### CODE REVIEW

**Comment by hadley** [comment]
I can also export if you want

**Comment by gaborcsardi** [comment]
Yeah, maybe we should export it, and use it in all the cli packages.

**Comment by gaborcsardi** [comment]
Btw. should we try to look up the terminal width? Personally, I would like that, because I am resizing the terminal often, and of course I don't update `width` manually.

The only problem is that we would need to ignore `width`, at least in terminals.

**Comment by hadley** [comment]
I'm certain I remember seeing a CRAN package that helped solve this problem somehow, but I can't find it again.

**Comment by gaborcsardi** [comment]
R / readline can in theory help. It did not work for me when I tried to set it up, I should try harder.

The terminal sends a SIGWINCH to the foreground process when the windows size changes. R is supposed to catch that, and adjust the windows size. Anyway, I'll try again.

**Pull request merged**
